### ISSUE TITLE
the Export Attribute seems useless?

### ISSUE THREAD

**Issue by zc910704** [phamtuanit/ModernWPF#1]
[https://github.com/phamtuanit/ModernWPF/blob/main/src/GoogleDrive/Views/MainWindow.xaml.cs](https://github.com/phamtuanit/ModernWPF/blob/main/src/GoogleDrive/Views/MainWindow.xaml.cs)
use the MEF Export Attribute , when i comment it,the code still worked, Can you explain what it is use for?

**Comment by phamtuanit** [comment]
You are right. That Export attribute is not necessary here. I already registered V/VM in Bostrapper at line #58.

**Comment by zc910704** [comment]
it seems all Export Attribute are not necessary?  and thanks for the demo, it helps a lot.
